version: "3"

services:
  server-account:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-account
    restart: always
    depends_on:
      - postgres-auth
    env_file:
      - backend/AccountingService/.docker.account.postgres.env
      - backend/AccountingService/.docker.account.env
      - backend/AccountingService/.docker.broker.env
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ${STATIC_PATH}:/usr/src/app/AccountProject/static
      - ${FILES_PATH}:/usr/src/app/AccountProject/files
    environment:
      - POSTGRES_HOST=postgres-auth
    command: bash -c '/usr/src/app/start.sh'

  server-auth:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-auth
    restart: always
    depends_on:
      - postgres-auth
    env_file:
      - backend/AuthenticationService/.docker.auth.postgres.env
      - backend/AuthenticationService/.docker.auth.env
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - ${STATIC_PATH}:/usr/src/app/AccountProject/static
    environment:
      - POSTGRES_HOST=postgres-auth
    command: bash -c '/usr/src/app/start.sh'

  server-info-composite:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-info-composite
    restart: always
    depends_on:
      - postgres-composite
    env_file:
      - backend/InfoCompositeOutputDataRESTAPIService/.docker.composite.postgres.env
      - backend/InfoCompositeOutputDataRESTAPIService/.docker.composite.env
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8002:8000"
    environment:
      - POSTGRES_HOST=postgres-composite
    command: bash -c '/usr/src/app/start.sh'

  server-composite-data:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-composite-data
    restart: always
    depends_on:
      - postgres-composite-data
    env_file:
      - backend/CompositeDataRESTAPIService/.docker.composite-data.postgres.env
      - backend/CompositeDataRESTAPIService/.docker.composite-data.env
      - backend/CompositeDataRESTAPIService/.docker.broker.env
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8003:8000"
    volumes:
      - type: bind
        source: ${PATH_TIFF_IMAGE}
        target: ${PATH_TIFF_IMAGE}
      - composite-data-files:/usr/src/app/files
    environment:
      - POSTGRES_HOST=postgres-composite-data
    command: bash -c '/usr/src/app/start.sh'

  server-docs-agregator:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-docs-agregator
    restart: always
    depends_on:
      - postgres-composite
    env_file:
      - backend/DocsAgregatorSwaggerUI/.docker.docs-swagger.env
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8004:8000"
    volumes:
      - ${STATIC_PATH}:/usr/src/app/AccountProject/static
    command: bash -c '/usr/src/app/start.sh'

  celery-worker:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: celery
    restart: unless-stopped
    command: bash -c '/usr/src/app/venv/bin/celery -A CeleryApp.app worker --loglevel=info -c 4 -n celery-worker'
    depends_on:
      - redis
    env_file:
      - backend/AccountingService/.docker.account.postgres.env
      - backend/AccountingService/.docker.account.env
      - backend/AccountingService/.docker.broker.env

  celery-worker-composite-data:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: celery-composite-data
    restart: unless-stopped
    command: bash -c '/usr/src/app/venv/bin/celery -A api.celery.app:celery_app worker --beat --loglevel=info -c 4 -n celery-worker-coposite-data'
    depends_on:
      - redis
    env_file:
      - backend/CompositeDataRESTAPIService/.docker.composite-data.postgres.env
      - backend/CompositeDataRESTAPIService/.docker.composite-data.env
      - backend/CompositeDataRESTAPIService/.docker.broker.env
    volumes:
      - type: bind
        source: ${PATH_TIFF_IMAGE}
        target: ${PATH_TIFF_IMAGE}
      - composite-data-files:/usr/src/app/files

  redis:
    image: redis:8.0.3
    restart: always
    command: redis-server
    expose:
      - "6379"

  postgres-auth:
    image: postgres:17.6
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql.conf
    expose:
      - "5432"
    env_file:
      - backend/AuthenticationService/.docker.auth.postgres.env
    volumes:
      - auth-db-volume:/var/lib/postgresql/data/
      - ./backend/postgresql/pg_hba.conf:/etc/postgres/pg_hba.conf
      - ./backend/postgresql/postgresql.conf:/etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-composite:
    image: postgres:17.6
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - backend/InfoCompositeOutputDataRESTAPIService/.docker.composite.postgres.env
    volumes:
      - composite-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-composite-data:
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - backend/CompositeDataRESTAPIService/.docker.composite-data.postgres.env
    volumes:
      - composite-data-db-volume:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-algmanager:
    image: postgres:17.6
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - backend/AlgorithmManagerService/.docker.algm.postgres.env
    volumes:
      - algmanager-db-volume:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.Dockerfile
    container_name: frontend
    volumes:
      - ${FRONTEND_BUILD_PATH}:/usr/src/app/frontend/dist
    profiles:
      - donotstart

volumes:
  auth-db-volume:
  composite-db-volume:
  composite-data-db-volume:
  composite-data-files:
  download-db:
  algmanager-db-volume:
  frontend-volume:
