services:
  nginx:
    restart: always
    image: nginx:1.29
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx-certbot.conf:/usr/src/app/nginx/conf.d/default.conf
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
      - ${CERTBOT_PATH}:/var/www/certbot
    command: /bin/bash -c "envsubst '$${SERVER_NAME}' < /usr/src/app/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --reinstall --webroot --webroot-path=/var/www/certbot --email $EMAIL --agree-tos --no-eff-email -d $SERVER_NAME
    depends_on:
      - nginx
    volumes:
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
      - ${CERTBOT_PATH}:/var/www/certbot

  certbot-renewal:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --force-renewal -d $SERVER_NAME
    volumes:
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
      - ${CERTBOT_PATH}:/var/www/certbot