services:

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --reinstall --webroot --webroot-path=/var/www/certbot --email $EMAIL --agree-tos --no-eff-email -d $SERVER_NAME
    volumes:
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
      - ${CERTBOT_PATH}:/var/www/certbot

  certbot-renewal:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --force-renewal -d $SERVER_NAME
    volumes:
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
      - ${CERTBOT_PATH}:/var/www/certbot