version: "3"

services:
  nginx:
    image: nginx:1.29
    restart: unless-stopped
    ports:
      - "0.0.0.0:${NGINX_SERVER_PORT}:${NGINX_SERVER_PORT}"
    depends_on:
#      - frontend
      - server-auth
    env_file:
      - .docker.nginx.env
    volumes:
      - ./nginx/conf.d/default.conf:/usr/src/app/nginx/conf.d/default.conf
      - etc-letsencrypt:/etc/letsencrypt/
      - static-volume:/usr/src/app/AccountProject/static
      - files-volume:/usr/src/app/AccountProject/files
      - ${PATH_TO_TILES}:/usr/src/tiles/
      - ${PATH_TO_RU_REGIONS_JSON}:/usr/src/ru-regions-json/
      - frontend-volume1:/usr/src/app/frontend/build
    command: /bin/bash -c "envsubst '$${SERVER_NAME},$${SERVER_PORT},$${SSL_CERTIFICATE_PATH},$${SSL_CERTIFICATE_KEY_PATH}' < /usr/src/app/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  server-account:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-account
    restart: always
    depends_on:
      - postgres-auth
    env_file:
      - backend/AccountingService/.docker.account.postgres.env
      - backend/AccountingService/.docker.account.env
      - backend/AccountingService/.docker.broker.env
    expose:
      - "8000"
    volumes:
      - ./backend/AccountingService/AccountProject/:/usr/src/app/AccountProject/
      - static-volume:/usr/src/app/AccountProject/static
      - files-volume:/usr/src/app/AccountProject/files
    environment:
      - POSTGRES_HOST=postgres-auth
    command: bash -c '/usr/src/app/start.sh'

  server-auth:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-auth
    restart: always
    depends_on:
      - postgres-auth
    env_file:
      - backend/AuthenticationService/.docker.auth.postgres.env
      - backend/AuthenticationService/.docker.auth.env
    expose:
      - "8000"
    volumes:
      - ./backend/AuthenticationService/AccountProject/:/usr/src/app/AccountProject/
      - static-volume:/usr/src/app/AccountProject/static
    environment:
      - POSTGRES_HOST=postgres-auth
    command: bash -c '/usr/src/app/start.sh'

  server-info-composite:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-info-composite
    restart: always
    depends_on:
      - postgres-composite
    env_file:
      - backend/InfoCompositeOutputDataRESTAPIService/.docker.composite.postgres.env
      - backend/InfoCompositeOutputDataRESTAPIService/.docker.composite.env
    expose:
      - "8000"
    volumes:
      - ./backend/InfoCompositeOutputDataRESTAPIService/api/:/usr/src/app/api/
    environment:
      - POSTGRES_HOST=postgres-composite
    command: bash -c '/usr/src/app/start.sh'

  server-composite-data:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-composite-data
    restart: always
    depends_on:
      - postgres-composite-data
    env_file:
      - backend/CompositeDataRESTAPIService/.docker.composite-data.postgres.env
      - backend/CompositeDataRESTAPIService/.docker.composite-data.env
      - backend/CompositeDataRESTAPIService/.docker.broker.env
    expose:
      - "8000"
    volumes:
      - ./backend/CompositeDataRESTAPIService/api/:/usr/src/app/api/
      - type: bind
        source: ${PATH_TIFF_IMAGE}
        target: ${PATH_TIFF_IMAGE}
      - composite-data-files:/usr/src/app/files
    environment:
      - POSTGRES_HOST=postgres-composite-data
    command: bash -c '/usr/src/app/start.sh'

  server-docs-agregator:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: server-docs-agregator
    restart: always
    depends_on:
      - postgres-composite
    env_file:
      - backend/DocsAgregatorSwaggerUI/.docker.docs-swagger.env
    expose:
      - "8000"
    volumes:
      - static-volume:/usr/src/app/AccountProject/static
    command: bash -c '/usr/src/app/start.sh'

  celery-worker:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: celery
    restart: unless-stopped
    command: bash -c '/usr/src/app/venv/bin/celery -A CeleryApp.app worker --loglevel=info -c 4 -n celery-worker'
    depends_on:
      - redis
    env_file:
      - backend/AccountingService/.docker.account.postgres.env
      - backend/AccountingService/.docker.account.env
      - backend/AccountingService/.docker.broker.env

  celery-worker-composite-data:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
      target: celery-composite-data
    restart: unless-stopped
    command: bash -c '/usr/src/app/venv/bin/celery -A api.celery.app:celery_app worker --beat --loglevel=info -c 4 -n celery-worker-coposite-data'
    depends_on:
      - redis
    env_file:
      - backend/CompositeDataRESTAPIService/.docker.composite-data.postgres.env
      - backend/CompositeDataRESTAPIService/.docker.composite-data.env
      - backend/CompositeDataRESTAPIService/.docker.broker.env
    volumes:
      - type: bind
        source: ${PATH_TIFF_IMAGE}
        target: ${PATH_TIFF_IMAGE}
      - composite-data-files:/usr/src/app/files
  redis:
    image: redis:8.0.3
    restart: always
    command: redis-server
    expose:
      - "6379"

  postgres-auth:
    image: postgres:17.6
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql.conf
    expose:
      - "5432"
    env_file:
      - backend/AuthenticationService/.docker.auth.postgres.env
    volumes:
      - auth-db-volume:/var/lib/postgresql/data/
      - ./backend/postgresql/pg_hba.conf:/etc/postgres/pg_hba.conf
      - ./backend/postgresql/postgresql.conf:/etc/postgresql.conf

  postgres-composite:
    image: postgres:17.6
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - backend/InfoCompositeOutputDataRESTAPIService/.docker.composite.postgres.env
    volumes:
      - composite-db-volume:/var/lib/postgresql/data

  postgres-composite-data:
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - backend/CompositeDataRESTAPIService/.docker.composite-data.postgres.env
    volumes:
      - composite-data-db-volume:/var/lib/postgresql/data/

  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.Dockerfile
    container_name: frontend
    volumes:
      - frontend-volume1:/usr/src/app/frontend/build
    profiles:
      - donotstart

  aria2-ui:
    image: hurlenko/aria2-ariang
    container_name: aria2-webui
    restart: always
    ports:
      - "6800:6800"      # Порт для RPC (подключение интерфейса к Aria2)
      - "8080:8080"      # Порт самого веб-интерфейса (открывать в браузере)
    environment:
      - PUID=1000        # ID вашего пользователя в Linux (чтобы не было проблем с правами на файлы)
      - PGID=1000        # ID группы вашего пользователя
      - RPC_SECRET=my_super_secret_token
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=admin
    volumes:
      - download-db:/aria2/data
    profiles:
      - donotstart

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=1000 #"id $user" to find your uid & gid values
      - PGID=1000
    ports:
      - 8081:80 #default port is 8080, change as needed. Don't change the right hand side port (port 80)
    volumes:
      - ${PATH_FILE_TRACK_DIR}:/srv
    restart: unless-stopped
    profiles:
      - donotstart

volumes:
  auth-db-volume:
  composite-db-volume:
  composite-data-db-volume:
  composite-data-files:
  static-volume:
  files-volume:
  etc-letsencrypt:
  frontend-volume1:
  download-db:
