# Generated by Django 5.2.17 on 2026-09-01 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя алгоритма')),
                ('description', models.TextField(blank=True, verbose_name='Описание алгоритма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('script_path', models.CharField(max_length=500, verbose_name='Путь до скрипта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Алгоритм',
                'verbose_name_plural': 'Алгоритмы',
                'db_table': 'algorithm',
            },
        ),
        migrations.CreateModel(
            name='InputFileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('source', models.CharField(choices=[('local', 'Локальная загрузка'), ('http', 'HTTP(S)'), ('ftp', 'FTP')], default='local', max_length=10, verbose_name='Источник')),
                ('source_url', models.CharField(blank=True, default='', max_length=1024, verbose_name='Исходный URL')),
                ('ftp_username', models.CharField(blank=True, default='', max_length=255, verbose_name='FTP логин')),
                ('ftp_password', models.CharField(blank=True, default='', max_length=1024, verbose_name='FTP пароль (signed)')),
                ('download_status', models.CharField(choices=[('queued', 'В очереди'), ('downloading', 'Скачивается'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='completed', max_length=20, verbose_name='Статус загрузки')),
                ('download_error', models.TextField(blank=True, default='', verbose_name='Ошибка загрузки')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Входной файл',
                'verbose_name_plural': 'Входные файлы',
                'db_table': 'input_file',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя опции алгоритма')),
                ('description', models.TextField(blank=True, verbose_name='Описание алгоритма')),
                ('option', models.CharField(max_length=50, verbose_name='Опция для алгоритма')),
                ('example_value', models.CharField(max_length=255, verbose_name='Пример значения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algorithmmodel', verbose_name='Алгоритм')),
            ],
            options={
                'verbose_name': 'Опция алгорита',
                'verbose_name_plural': 'Опции алгоритма',
                'db_table': 'algorithm_options',
            },
        ),
        migrations.CreateModel(
            name='ProcessingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_path', models.CharField(blank=True, max_length=500, verbose_name='Директория результат')),
                ('status', models.CharField(choices=[('pending', 'Ожидает запуска'), ('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершён успешно'), ('failed', 'Завершён с ошибкой'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('log_file', models.CharField(blank=True, max_length=500, verbose_name='Путь к логу')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выполнения')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.algorithmmodel', verbose_name='Алгоритм')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запуск алгоритма',
                'verbose_name_plural': 'Запуски алгоритмов',
                'db_table': 'processing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingArgOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_order', models.PositiveSmallIntegerField(default=0, help_text='Позиция аргумента в командной строке (порядок из формы)', verbose_name='Позиция')),
                ('value', models.CharField(blank=True, default='', help_text='Текстовое значение или путь к файлу (снапшот на момент запуска)', max_length=1024, verbose_name='Значение')),
                ('option', models.CharField(max_length=50, verbose_name='Опция для алгоритма')),
                ('arg_type', models.CharField(choices=[('value', 'Значение (текст)'), ('file', 'Файл'), ('flag', 'Флаг (без значения)')], default='value', max_length=10, verbose_name='Тип значения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('input_file', models.ForeignKey(blank=True, help_text='Файл из системы, выбранный как значение аргумента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_arguments', to='core.inputfilemodel', verbose_name='Файл')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processingmodel', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Дополнительный аргумент запуска',
                'verbose_name_plural': 'Дополнительные аргументы запуска',
                'db_table': 'processing_arg_option',
                'ordering': ['argument_order'],
            },
        ),
    ]
