# Generated by Django 5.2.17 on 2026-09-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmmodel',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='processingmodel',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='core.algorithmmodel', verbose_name='Алгоритм'),
        ),
    ]
