# Generated by Django 5.2.17 on 2026-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inputfilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfilemodel',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='input_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
