# Generated by Django 5.2.17 on 2026-09-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inputfilemodel_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmoptionmodel',
            name='example_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пример значения'),
        ),
    ]
