# Generated by Django 5.2.17 on 2026-09-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_algorithmoptionmodel_example_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
