# Generated by Django 5.2.17 on 2026-09-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_id_processingmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingargoptionmodel',
            options={'ordering': ['argument_order'], 'verbose_name': 'Аргумент запуска', 'verbose_name_plural': 'Аргументы запуска'},
        ),
        migrations.AddField(
            model_name='processingmodel',
            name='current_step',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текущий шаг'),
        ),
        migrations.AlterField(
            model_name='processingargoptionmodel',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.processingmodel', verbose_name='Запуск'),
        ),
    ]
