# Generated by Django 5.2.17 on 2026-09-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_processingargoptionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingargoptionmodel',
            name='input_file',
            field=models.ForeignKey(blank=True, help_text='Файл из системы, выбранный как значение аргумента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_arguments', to='core.inputfilemodel', verbose_name='Файл'),
        ),
    ]
