# Generated by Django 5.2.17 on 2026-09-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_processingargoptionmodel_input_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingmodel',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Прогресс (%)'),
        ),
    ]
