# Generated by Django 5.2.17 on 2026-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_processingmodel_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingargoptionmodel',
            name='arg_type',
            field=models.CharField(choices=[('value', 'Значение (текст)'), ('file_arg', 'Файл'), ('file', 'Файл (без аргумента)'), ('flag', 'Флаг (без значения)')], default='value', max_length=10, verbose_name='Тип значения'),
        ),
        migrations.AlterField(
            model_name='processingmodel',
            name='output_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Директория результата'),
        ),
        migrations.AlterField(
            model_name='processingmodel',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец выполнения'),
        ),
    ]
