# Generated by Django 5.2.17 on 2026-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_processingargoptionmodel_arg_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmmodel',
            name='script_path',
            field=models.FileField(upload_to='', verbose_name='Путь до скрипта'),
        ),
    ]
