# Generated by Django 5.2.17 on 2026-09-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_algorithmmodel_script_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingargoptionmodel',
            name='use_sudo',
            field=models.BooleanField(default=False, help_text='Выполнять скрипт с префиксом sudo и выбранными опциями sudo', verbose_name='Запускать с sudo'),
        ),
        migrations.AddField(
            model_name='processingmodel',
            name='use_sudo',
            field=models.BooleanField(default=False, help_text='Выполнять скрипт с префиксом sudo и выбранными опциями sudo', verbose_name='Запускать с sudo'),
        ),
        migrations.AlterField(
            model_name='algorithmmodel',
            name='script_path',
            field=models.CharField(max_length=500, verbose_name='Путь до скрипта'),
        ),
    ]
