# Generated by Django 5.2.17 on 2026-09-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_processingargoptionmodel_use_sudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmoptionmodel',
            name='arg_type',
            field=models.CharField(choices=[('value', 'Значение (текст)'), ('file_arg', 'Файл'), ('file', 'Файл (без аргумента)'), ('flag', 'Флаг (без значения)')], default='value', max_length=10, verbose_name='Тип значения'),
        ),
    ]
