# Generated by Django 5.2.17 on 2026-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_algorithmoptionmodel_arg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingmodel',
            name='log_file',
            field=models.FilePathField(blank=True, max_length=500, null=True, path='media/logs', verbose_name='Путь к логу'),
        ),
    ]
