# Generated by Django 5.2.17 on 2026-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_processingmodel_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmmodel',
            name='max_parallel_processes',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Макс. количество параллельных процесов для выполняемых, используя алгоритм'),
        ),
    ]
