# Generated by Django 4.2.26 on 2026-06-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0011_usermodel_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/profile/image'),
        ),
    ]
