# Generated by Django 4.2.26 on 2026-06-23 04:31

import AccountApp.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0013_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=75, scale=None, size=[500, 500], upload_to=AccountApp.models.upload_to),
        ),
    ]
