"""add autoincrement userfilecomposite

Revision ID: a568e6c0b795
Revises: cdf5b87086db
Create Date: 2026-06-11 17:09:29.045088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a568e6c0b795'
down_revision: Union[str, Sequence[str], None] = 'cdf5b87086db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE user_file_composite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('user_file_composite', 'id'), COALESCE(max(id), 1)) FROM user_file_composite;"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE user_file_composite ALTER COLUMN id DROP IDENTITY IF EXISTS;"
    )