"""Create composit_polygon table

Revision ID: ac7d3d7bafb7
Revises: 507d25fcd0ff
Create Date: 2026-05-25 00:28:02.422064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'ac7d3d7bafb7'
down_revision: Union[str, Sequence[str], None] = '507d25fcd0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_polygon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polygon', Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('file_composite', sa.Column('composite_polygon_id', sa.Integer(), nullable=False))
    op.drop_column('file_composite', 'polygon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_composite', sa.Column('polygon', Geometry(geometry_type='POLYGON', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_column('file_composite', 'composite_polygon_id')
    op.drop_table('composite_polygon')
    # ### end Alembic commands ###
