"""add datetime_expiration field

Revision ID: b87917fb0545
Revises: ac7d3d7bafb7
Create Date: 2026-05-25 01:01:56.218177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b87917fb0545'
down_revision: Union[str, Sequence[str], None] = 'ac7d3d7bafb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'composite_polygon', ['id'])
    op.add_column('user_file_composite', sa.Column('datetime_expiration', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_file_composite', 'datetime_expiration')
    op.drop_constraint(None, 'composite_polygon', type_='unique')
    # ### end Alembic commands ###
