"""polygon to multipolygon

Revision ID: bd372dce57e0
Revises: b87917fb0545
Create Date: 2026-06-02 10:56:53.154516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'bd372dce57e0'
down_revision: Union[str, Sequence[str], None] = 'b87917fb0545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('composite_polygon', 'polygon',
               existing_type=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('composite_polygon', 'polygon',
               existing_type=Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
