"""add download-link

Revision ID: cdf5b87086db
Revises: bd372dce57e0
Create Date: 2026-06-11 13:09:19.011353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cdf5b87086db'
down_revision: Union[str, Sequence[str], None] = 'bd372dce57e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user_file_composite', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_file_composite', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('user_file_composite_uid_key'), 'user_file_composite', type_='unique')
    op.create_primary_key(None, 'user_file_composite', ['id'])
    op.drop_column('user_file_composite', 'uid')

    op.create_table('download_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('file_composite_id', sa.Integer(), nullable=True),
    sa.Column('user_file_composite_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime_expiration', sa.DateTime(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_composite_id'], ['file_composite.id'], ),
    sa.ForeignKeyConstraint(['user_file_composite_id'], ['user_file_composite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('download_history', sa.Column('download_link_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('download_history_file_composite_id_fkey'), 'download_history', type_='foreignkey')
    op.create_foreign_key(None, 'download_history', 'download_link', ['download_link_id'], ['id'])
    op.drop_column('download_history', 'file_composite_id')
    op.drop_column('download_history', 'user_polygon')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('download_history', sa.Column('user_polygon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('download_history', sa.Column('file_composite_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'download_history', type_='foreignkey')
    op.create_foreign_key(op.f('download_history_file_composite_id_fkey'), 'download_history', 'file_composite', ['file_composite_id'], ['id'])
    op.drop_column('download_history', 'download_link_id')
    op.drop_table('download_link')

    op.add_column('user_file_composite', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'user_file_composite', type_='unique')
    op.create_unique_constraint(op.f('user_file_composite_uid_key'), 'user_file_composite', ['uid'])
    op.drop_column('user_file_composite', 'deleted')
    op.drop_column('user_file_composite', 'id')

    # ### end Alembic commands ###
